language: node_js
node_js:
  - "6.0.0"
sudo: enabled
dist: trusty
addons:
  apt:
    packages:
      - sshpass
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g bower grunt-cli codacy-coverage coveralls
  - bower install --force
after_script:
  - cat coverage/**/lcov.info | codacy-coverage
  - cat coverage/**/lcov.info | coveralls
before_deploy:
  - gulp build:package
  -
deploy:
  - provider: bintray
    file: "bintray.json"
    user: "psbrandt"
    key: $BINTRAY_API_KEY
    dry-run: false
    on:
      branch: master
  - provider: bintray
    file: "bintray-release.json"
    user: "psbrandt"
    key: $BINTRAY_API_KEY
    dry-run: false
    on:
      tags: true
after_deploy:
  -
  -  
